name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate secrets
        run: |
          for secret in SSH_PRIVATE_KEY SERVER_USER SERVER_IP GIT_USERNAME GIT_TOKEN; do
            if [ -z "$(eval echo \$\{$secret\})" ]; then
              echo "Error: $secret is empty or not set"
              exit 1
            fi
          done
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o ConnectTimeout=30 -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            
            echo "Starting deployment..."
            
            cd /home/arthur-moraes/WX2TB/Documentos/fontes/PMO/raizen-power-trading-api-webhook-sintegre || exit 1
            
            git config --local credential.helper '!f() { echo "username=${{ secrets.GIT_USERNAME }}"; echo "password=${{ secrets.GIT_TOKEN }}"; }; f'
            
            echo "Pulling latest changes..."
            git pull origin main || exit 1
            
            git config --local --unset credential.helper
            
            echo "Building and starting containers..."
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            echo "Verifying deployment..."
            sleep 5
            if sudo docker-compose ps | grep -q "Up"; then
              echo "Deployment successful!"
            else
              echo "Deployment may have failed - check container status"
              sudo docker-compose logs --tail=20
              exit 1
            fi
          EOF

      - name: Cleanup SSH keys
        if: always()
        run: |
          rm -f ~/.ssh/id_rsa
