name: Publish TechDocs Site

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yaml'

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Kind
        id: catalog-kind
        uses: devorbitus/yq-action-output@v1.1
        with:
          cmd: yq eval '.kind' 'catalog-info.yaml'

      - name: Get Metadata.Name
        id: catalog-metadata-name
        uses: devorbitus/yq-action-output@v1.1
        with:
          cmd: yq eval '.metadata.name' 'catalog-info.yaml'

      - name: Backstage TechDocs
        uses: Staffbase/backstage-techdocs-action@v0.2.0
        with:
          entity-namespace: 'default'
          entity-kind: ${{ steps.catalog-kind.outputs.result }}
          entity-name: ${{ steps.catalog-metadata-name.outputs.result }}
          publisher-type: 'azureBlobStorage'
          storage-name: ${{ secrets.TECHDOCS_CONTAINER_NAME }}
          azure-account-name: ${{ secrets.TECHDOCS_STORAGE_ACCOUNT }}
          azure-account-key: ${{ secrets.TECHDOCS_AZURE_ACCESS_KEY }}